name: Release

on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Run lint tasks
        run: pnpm lint

  publish:
    name: Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Run build
        run: pnpm build
      - name: Deploy semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release
