name: Release

on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: pnpm lint

  tests:
    name: Tests Node ${{ matrix.node }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm test:coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        if: ${{ !cancelled() }}
        with:
          file-coverage-mode: all
          pr-number: auto
          threshold-icons: "{0: '🟠', 80: '🟡', 90: '⚪'}"
    strategy:
      matrix:
        node: [22, 24, 26]
        os: [macos-latest, ubuntu-latest, windows-latest]

  publish:
    name: Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [lint, tests]
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: pnpm build
      - run: pnpx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
